export type Enc={k:'choose'|'build'|'listen'|'meaning'|'convo';line?:string;q:string;o?:string[];a?:number;w?:string[];v?:string[];h:string;e:string}
export type Chapter={id:string;t:string;place:string;intro:string;skills:string[];enc:Enc[]}
export const chapters:Chapter[]=[
{id:'first-day',t:'First Day',place:'Harbour City, your new street',intro:"You have just arrived in Harbour City. A neighbour, Maya, waves from the next door. Time to introduce yourself.",skills:['Introducing yourself','Asking polite questions'],enc:[
{k:'choose',line:"Hi! I'm Maya. What's your name?",q:"Choose the most natural reply.",o:["My name is Sam. Nice to meet you.","I am name Sam.","Sam my name is called."],a:0,h:"Start with a full, simple sentence.",e:"'My name is… Nice to meet you.' is natural and friendly. The others use the wrong word order."},
{k:'build',q:"Build the question: ask where Maya is from.",w:["from","you","are","Where"],v:["where are you from"],h:"The question word comes first.",e:"In questions the verb 'are' comes before 'you': Where are you from?"},
{k:'listen',line:"Are you new in the city?",q:"What is Maya asking?",o:["If you are new here","Where your house is","What time it is"],a:0,h:"'New' and 'city' are the key words.",e:"'Are you new in the city?' asks whether you have just arrived."},
{k:'convo',line:"I'm a designer. What do you do?",q:"Reply and keep the conversation going.",o:["I'm a student. What about you?","Yes, I do.","Student I am."],a:0,h:"Answer, then ask something back.",e:"'What about you?' keeps a conversation moving. 'Yes, I do' does not answer 'What do you do?'."}]},
{id:'cafe',t:'The Café',place:'Corner Café',intro:"You need coffee. The café is busy and the barista speaks quickly. Order politely and ask when you are not sure.",skills:['Ordering politely','Clarifying and replying to problems'],enc:[
{k:'choose',line:"What can I get you?",q:"Choose the most polite order.",o:["Can I have a small coffee, please?","Give coffee me.","I want coffee now."],a:0,h:"Polite orders often start with 'Can I have'.",e:"'Can I have… please?' is polite and clear. 'I want… now' sounds rude."},
{k:'build',q:"Build the sentence: politely ask for a large tea.",w:["please","tea","a","Could","I","have","large"],v:["could i have a large tea please","can i have a large tea please"],h:"Start with 'Could' or 'Can', then 'I'.",e:"Requests use 'Could/Can I have…'. Adjectives like 'large' come before the noun."},
{k:'meaning',line:"Would you like that for here or to go?",q:"What does 'to go' mean?",o:["Take it away with you","Pay later","Sit by the door"],a:0,h:"Think about someone leaving with a cup.",e:"'To go' means you take the food or drink away. 'For here' means you stay."},
{k:'convo',line:"Sorry, we're out of oat milk.",q:"Choose the best reply.",o:["No problem. Do you have soy milk?","Why not?","You are wrong."],a:0,h:"Stay friendly and offer a new choice.",e:"Accepting the problem and asking for an alternative is polite and useful."}]},
{id:'across-town',t:'Across Town',place:'Central Station',intro:"You need to reach the museum on the other side of town. You will ask for help and follow directions.",skills:['Asking for directions','Understanding transport and directions'],enc:[
{k:'choose',q:"Ask a stranger politely for the station.",o:["Excuse me, how do I get to the station?","Station where?","Tell station now."],a:0,h:"Begin with 'Excuse me'.",e:"'Excuse me' gets attention politely, and 'how do I get to…' is the standard direction question."},
{k:'listen',line:"Go straight, then turn left at the bank.",q:"Where do you turn?",o:["Left, at the bank","Right, before the bank","At the station"],a:0,h:"Listen for 'left' and 'bank'.",e:"'Turn left at the bank' means turn to the left when you reach the bank."},
{k:'build',q:"Build the question: ask if the bus stop is near.",w:["here","near","Is","stop","the","bus"],v:["is the bus stop near here"],h:"Start with the verb 'Is'.",e:"Yes/no questions start with the verb: Is the bus stop near here?"},
{k:'convo',line:"The number 5 bus goes downtown.",q:"You want the museum. Make sure politely.",o:["Sorry, does the number 5 stop at the museum?","Yes yes bus.","I no understand bus."],a:0,h:"Ask a clear yes/no question.",e:"A direct, polite question gets the information you need. The other replies do not ask anything."}]},
{id:'market',t:'The Market',place:'Saturday Market',intro:"The market is full of fruit, bread and bargains. Ask about prices, choose quantities and compare.",skills:['Prices and quantities','Comparing things'],enc:[
{k:'choose',line:"Those apples are two dollars a kilo.",q:"You want one kilo. Reply.",o:["I'll take one kilo, please.","One kilo is I want.","Apples me give."],a:0,h:"'I'll take…' is a natural way to decide.",e:"'I'll take one kilo, please' states quantity clearly and politely."},
{k:'meaning',line:"These are cheaper than those.",q:"What is being compared?",o:["Price: these cost less","Size: these are bigger","Colour: these are brighter"],a:0,h:"'Cheap' is about money.",e:"'Cheaper than' compares price. Adding -er and 'than' is how we compare short adjectives."},
{k:'build',q:"Build the question: ask the price of oranges.",w:["much","are","How","these","oranges"],v:["how much are these oranges"],h:"'How much' begins a price question.",e:"With plural nouns we say 'How much are…?' (How much is it? for one item)."},
{k:'convo',line:"That will be six dollars.",q:"The sign says five dollars. Say so politely.",o:["Sorry, the sign says five. Could you check?","That's wrong!","Too much, no."],a:0,h:"Apologise gently, give the fact, ask for help.",e:"Starting with 'Sorry' and asking 'Could you check?' solves the problem without an argument."}]},
{id:'plans',t:'Making Plans',place:'Riverside Park',intro:"You have made friends. Now they want to meet. You will talk about time, accept invitations and say no kindly.",skills:['Telling and understanding time','Invitations and responses'],enc:[
{k:'choose',line:"Are you free on Saturday?",q:"You are free and interested.",o:["Yes, I'm free. What's the plan?","Saturday is free me.","No free Saturday yes."],a:0,h:"Answer, then ask about the plan.",e:"A short 'Yes, I'm free' answers the question and 'What's the plan?' moves things forward."},
{k:'listen',line:"Let's meet at half past six.",q:"What time is it?",o:["6:30","5:30","6:15"],a:0,h:"'Half' means thirty minutes.",e:"'Half past six' is 6:30."},
{k:'build',q:"Build the sentence: say you cannot come on Friday.",w:["Friday","come","I'm","sorry","can't","I","on"],v:["i'm sorry i can't come on friday"],h:"Start with 'I'm sorry'.",e:"'I can't come on Friday' uses 'on' with a day of the week."},
{k:'convo',line:"Would you like to join us for dinner?",q:"You are busy but interested.",o:["I'd love to, but I'm busy. Can we do next week?","No.","Maybe I not."],a:0,h:"Decline kindly and offer another time.",e:"'I'd love to, but…' softens a refusal and suggesting another time keeps the friendship warm."}]},
{id:'opportunity',t:'The Big Opportunity',place:'Lumen Studio, meeting room',intro:"A design studio has invited you for an interview. Use everything you have learned: introduce yourself, listen carefully and ask good questions.",skills:['Talking about yourself and experience','Interview conversation'],enc:[
{k:'choose',line:"Thanks for coming. Please tell me about yourself.",q:"Choose the strongest answer.",o:["I'm a designer, and I enjoy solving problems with teams.","Me designer good.","What about you?"],a:0,h:"Give your job and one thing you enjoy.",e:"A complete sentence with a role and a strength gives the interviewer something to work with."},
{k:'listen',line:"Can you tell me about a challenge you solved?",q:"What does the interviewer want?",o:["An example from your experience","Your home address","A phone number"],a:0,h:"'Challenge you solved' means a past problem.",e:"They want a real example of a problem you handled."},
{k:'build',q:"Build the sentence: say you have two years of experience.",w:["have","of","two","years","I","experience"],v:["i have two years of experience"],h:"Start with 'I have'.",e:"Use 'years of experience' after the number."},
{k:'convo',line:"Do you have any questions for us?",q:"Choose the best reply.",o:["Yes. What would my first month look like?","No. Bye.","How much money?"],a:0,h:"Ask about the job itself.",e:"A question about the role shows interest. Pay matters, but starting with money can seem too abrupt."}]}]
